version: '3.5'

services:
  postgres:
    container_name: postgres12
    image: postgres:12-alpine
    environment:
      POSTGRES_DB: simple_bank
      POSTGRES_USER: root
      POSTGRES_PASSWORD: mysecretpassword
      PGDATA: /data/postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped